name: (Backup) Build and commit WebGL in same branch

on:
  push:
    branches: [ backup ]
env:
 UNITY_LICENSE : ${{secrets.UNITY_LICENSE_2019}}
 UNITY_VERSION : 2019.4.10f1
 PROJECT_PATH  : Phong/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Unity Builder
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          allowDirtyBuild: true # TODO - investigate why branch is always dirty
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: WebGL
          buildsPath: .
          buildName: WebBuild
          customImage: 'amoghsubhedar/unity-webgl-editor:latest'

      - name: Deploy WebGL build on github pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy web build
          file_pattern: WebGL/WebBuild/Build/* WebGL/WebBuild/TemplateData/*
           # Optional: Skip internal call to `git fetch`
          skip_fetch: true