name: (Backup) Build and commit WebGL in same branch

on:
  push:
    branches: [ backup ]
env:
 UNITY_LICENSE : ${{secrets.UNITY_LICENSE_2019}}
 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Store library in cache
      - uses: actions/cache@v2
        with:
          path: ./Phong/Library
          key: Library-Phong-WebGL
          restore-keys: |
            Library-Phong-
            Library-
        
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-5
        with:
          allowDirtyBuild: true # TODO - investigate why branch is always dirty
          projectPath: Phong/
          unityVersion: 2019.4.10f1
          targetPlatform: WebGL
          buildsPath: .
          buildName: WebBuild
          
      - name: Deploy WebGL build on github pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy web build
          file_pattern: WebGL/WebBuild/Build/* WebGL/WebBuild/TemplateData/*
           # Optional: Skip internal call to `git fetch`
          skip_fetch: true
