
name: Build and upload WebGL artifact

on:
  push:
    branches: [ main ]
env:
 UNITY_LICENSE : ${{secrets.UNITY_LICENSE_2019}}
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      #  Store library in cache
      - uses: actions/cache@v2
        with:
          path: ./Phong/Library
          key: Library-Phong/-WebGL
          restore-keys: |
            Library-Phong/-
            Library-
        
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          allowDirtyBuild: true # TODO - investigate
          projectPath: Phong/
          unityVersion: 2019.4.10f1
          targetPlatform: WebGL
          buildsPath: .
          buildName: WebBuild
          
      - name: Show git status
        run : git status
  
      - name: Get rid of lib files before checking out builds branch
        run : git rm -r -f Phong/
             
      - name: Setup ownership for build directory
        run : sudo chown -R $USER WebGL/
        
      - name: Setup perms for build directory
        run : sudo chmod -R u+rw WebGL/
        
      - name: Track all changes
        run : git add .
        
      - name: Show git status
        run : git status
        
      - name: Stash the WebGL folder
        run : git stash
      
      - name: Show git status
        run : git status
        
      - name: Checkout builds branch
        uses : actions/checkout@v2
        with :
          ref: builds
          
      - name: Apply stashed changes
        run : git stash pop
  
      - name: Deploy WebGL build on github pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy web build
          file_pattern: WebGL/WebBuild/Build/* WebGL/WebBuild/TemplateData/*
           # Optional: Skip internal call to `git fetch`
          skip_fetch: true
          
    #  - uses: actions/upload-artifact@v1
     #   with:
      #    name: WebBuild
       #   path: Build
