# This is a basic workflow to help you get started with Actions

name: Build and upload WebGL artifact

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
env:
 UNITY_LICENSE : ${{secrets.UNITY_LICENSE_2019}}
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - uses: actions/cache@v2
        with:
          path: ./Phong/Library
          key: Library-Phong/-WebGL
          restore-keys: |
            Library-Phong/-
            Library-
        
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          allowDirtyBuild: true
          projectPath: ./Phong/
          unityVersion: 2019.4.10f1
          targetPlatform: WebGL
          
      - uses: actions/upload-artifact@v1
        with:
          name: WebGLBuild
          path: build/WebGL
